title = "example"

[character]
name = "example"
password = "character password" # NOTE: storing passwords in this way is insecure.

[connect]
address = "mud address"
auto_login = ["y","$user","$pass","y"] # Auto-login commands, requires storing password.

[aliases]
    # Single line alias
    [aliases.ii]
    cmd = "ii"
    action = "i b"

    # Single line alias with wildcard
    [aliases.bag]
    cmd = "bag *"
    action = "put %1 in bag"

    # Multi-line alias
    [aliases.bb]
    cmd = "bb"
    action = '''
    board boat
    buy passage
    '''
